/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const User = IDL.Record({
  'username' : IDL.Text,
  'passwordHash' : IDL.Text,
  'sectionLevel' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'deleteUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'listUsers' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(User)], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const User = IDL.Record({
    'username' : IDL.Text,
    'passwordHash' : IDL.Text,
    'sectionLevel' : IDL.Nat,
  });
  
  return IDL.Service({
    'createUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'deleteUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'listUsers' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(User)], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };