/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Chart = IDL.Record({
  'id' : IDL.Nat,
  'dob' : IDL.Text,
  'name' : IDL.Text,
  'basicNumber' : IDL.Nat,
  'destinyNumber' : IDL.Nat,
  'chartNumbers' : IDL.Vec(IDL.Nat),
});

export const idlService = IDL.Service({
  'createChart' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'deleteChart' : IDL.Func([IDL.Nat], [], []),
  'getAllCharts' : IDL.Func([], [IDL.Vec(Chart)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Chart = IDL.Record({
    'id' : IDL.Nat,
    'dob' : IDL.Text,
    'name' : IDL.Text,
    'basicNumber' : IDL.Nat,
    'destinyNumber' : IDL.Nat,
    'chartNumbers' : IDL.Vec(IDL.Nat),
  });
  
  return IDL.Service({
    'createChart' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'deleteChart' : IDL.Func([IDL.Nat], [], []),
    'getAllCharts' : IDL.Func([], [IDL.Vec(Chart)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };